/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-01-24 03:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.entryPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.puppyrush.buzzcloud.page.enums.*;
import com.puppyrush.buzzcloud.page.*;
import java.util.HashMap;

public final class EntryPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.puppyrush.buzzcloud.page");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.puppyrush.buzzcloud.page.enums");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"full\" lang=\"ko\">\n");
      out.write("\n");
      out.write("<!-- Make sure the <html> tag is set to the .full CSS class. Change the background image in the full.css file. -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("<title>Start BuzzCloud</title>\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core CSS -->\n");
      out.write("<link\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"\trel=\"stylesheet\"\tintegrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link\n");
      out.write("\thref=\"css/mainpage.css?<?=filemtime(\\'./css/readizgen.css\\')?\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link\n");
      out.write("\thref=\"css/form.css?<?=filemtime(\\'./css/readizgen.css\\')?\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<!--  -->\n");
      out.write("\n");
      out.write("<!--  notificator include -->\n");
      out.write("<script src=\"/include/notificator/ohsnap.js\" type=\"text/javascript\"\tcharset=\"utf-8\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\thref=\"/include/notificator/ohsnap.css\" />\n");
      out.write("\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("\t\t        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("\t\t        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("\t\t    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"mask\"></div>\n");
      out.write("\n");
      out.write("\t<div class=\"joinModal\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"text-vertical-center\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\t\taria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\">버즈클라우드에 가입하기</h1>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<form class=\"form col-md-12 center-block\" id=\"innerJoinForm\"\t>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" id=\"email\" class=\"form-control input-lg\"\tplaceholder=\"Email\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"nickname\" id=\"nickname\" class=\"form-control input-lg\"\t\t\tplaceholder=\"Nickname\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\"\t id=\"password\"\tclass=\"form-control input-lg\" placeholder=\"Password\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password2\"\tid=\"password2\"\t\tclass=\"form-control input-lg\" placeholder=\"Rewrite Password\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\" id=\"joinButton\" type=\"button\"\t>가입하기 </button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"idType\" name=\"idType\" value=\"NOTHING\">\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">Cancel</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"logonModal\">\n");
      out.write("\t\t<div class=\"text-vertical-center\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\t\taria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\">버즈클라우드에 로그인</h1>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<form class=\"form col-md-12 center-block\" id=\"loginForm\"\tmethod=\"POST\" ACTION=\"login.do\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\"\t id=\"email\"\t\tclass=\"form-control input-lg\" placeholder=\"Email\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\"\tid=\"password\"\t\tclass=\"form-control input-lg\" placeholder=\"Password\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\"\t>로그인하기</button>\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-right\"><a href=\"#\" class=\"joinToBuzzCloud\">가입하기</a></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\"  id=\"idType\" name=\"idType\" value=\"NOTHING\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\"  id=\"nickname\" name=\"nickname\" >\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">Cancel</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Navigation -->\n");
      out.write("\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-bottom\"\trole=\"navigation\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> \n");
      out.write("\t\t\t\t\t<span\tclass=\"icon-bar\"></span> \n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> \n");
      out.write("\t\t\t\t\t<span\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">BuzzCloud</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">버즈클라우드?</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">어떻게 사용하죠?</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">문제점보고와 건의사항</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">개발자와 연락하기</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"joinToBuzzCloud\">버즈클라우드에 가입하기 </a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.container -->\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Page Content -->\n");
      out.write("\n");
      out.write("\t<header id=\"top\" class=\"header\">\n");
      out.write("\t\t<div class=\"text-vertical-center\">\n");
      out.write("\n");
      out.write("\t\t\t<h1>버즈클라우드</h1>\n");
      out.write("\t\t\t<h3>\n");
      out.write("\t\t\t\t생산적인 팀 프로젝트를 위해<br> 사용해보세요\n");
      out.write("\t\t\t</h3>\n");
      out.write("\t\t\t<br> <br> <input type=\"BUTTON\" id=\"loginTobuzzCloud\"\t\tclass=\"btn btn-dark btn-lg\" value=\"버즈클라우드 로그인하기 \"> <br> <br>\n");
      out.write("\t\t\t<div id=\"naver_id_login\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- /.container -->\n");
      out.write("\n");
      out.write("\t<div id=\"ohsnap\"></div>\n");
      out.write("\n");
      out.write("\t<form id=\"alreadyLoginForm\" method=\"GET\" action=\"/alreadyLogin.do\">\n");
      out.write("\t</form>  \n");
      out.write("\n");
      out.write("\t<!--  static library -->\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\"\t\tsrc=\"http://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\"\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\"\t\tsrc=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\n");
      out.write("\t<script \tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- custom library  -->\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\"\t\tsrc=\"/commanJs/clientSideLibrary.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" charset=\"utf-8\" src=\"/page/entryPage/js/entryPage.js\"></script>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\twindow.onload=function(){\n");
      out.write("\t\n");
      out.write("\t\t//메세지\n");
      out.write("\t\tvar message;\n");
      out.write("\t\tvar popup_color;\n");
      out.write("\t\t");
 
			if(request.getAttribute("message")!=null && request.getAttribute("messageKind") !=null){
				enumCautionKind kind = (enumCautionKind)request.getAttribute("messageKind");	
		
      out.write("\n");
      out.write("\t\t\t  message = \"");
      out.print((String)request.getAttribute("message"));
      out.write("\";\n");
      out.write("\t\t\t  popup_color = \"");
      out.print((String)kind.getString());
      out.write("\";\n");
      out.write("\t\t\t  ohSnap(message,{color:popup_color});\n");
      out.write("\t\t");

			}
		
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t   $.ajax({\n");
      out.write("\t\t\t\t   type:\"POST\",\n");
      out.write("\t\t\t\t   dataType:\"json\",\n");
      out.write("\t\t\t\t   url:'/page/member/ajax/alreadyLogin.jsp',\n");
      out.write("\t\t\t\t   success:function(data){\n");
      out.write("\t\t\t\t   \t\t\t\t\t   \t\n");
      out.write("\t\t   \t\t\tif(data[\"alreadyLogin\"]){\n");
      out.write("\t\t   \t\t\t\t$(\"#alreadyLoginForm\").submit();\t   \t\t\t\t\t\n");
      out.write("\t\t   \t\t\t\t}\n");
      out.write("\t\t\t\t   \t\n");
      out.write("\t\t\t          }\n");
      out.write("\t\t\t      });\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
